import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers"
import Nav from "@/components/ui/nav";
import { Toaster } from "@/components/ui/sonner"
import {
  QueryClientProvider,
  QueryClient,
} from '@tanstack/react-query'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-background overflow-hidden`}
      >
        <Providers>
          <main className="mx-12 my-6 overflow-hidden! min-h-lvh">
              <Nav/>
              {children}
          </main>
        <Toaster />
      </Providers>
      </body>
    </html>
  );
}
